// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package postgres

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type JobStatus string

const (
	JobStatusACTIVE     JobStatus = "ACTIVE"
	JobStatusPROCESSING JobStatus = "PROCESSING"
	JobStatusCOMPLETED  JobStatus = "COMPLETED"
	JobStatusCANCELLED  JobStatus = "CANCELLED"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type Job struct {
	ID          int64              `json:"id"`
	CustomID    pgtype.Text        `json:"custom_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Delay       int32              `json:"delay"`
	Repeat      int32              `json:"repeat"`
	Webhook     []byte             `json:"webhook"`
	Status      JobStatus          `json:"status"`
	Executions  int32              `json:"executions"`
	DeadlineAt  pgtype.Timestamptz `json:"deadline_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type JobLog struct {
	ID          int64              `json:"id"`
	JobID       int64              `json:"job_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	StatusCode  pgtype.Int4        `json:"status_code"`
	Reason      pgtype.Text        `json:"reason"`
	Payload     pgtype.Text        `json:"payload"`
	Error       pgtype.Text        `json:"error"`
	ErrorType   pgtype.Text        `json:"error_type"`
}
