// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    custom_id,
    delay,
    repeat,
    webhook,
    deadline_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, custom_id, created_at, updated_at, delay, repeat, webhook, status, executions, deadline_at, completed_at
`

type CreateJobParams struct {
	CustomID   pgtype.Text        `json:"custom_id"`
	Delay      int32              `json:"delay"`
	Repeat     int32              `json:"repeat"`
	Webhook    []byte             `json:"webhook"`
	DeadlineAt pgtype.Timestamptz `json:"deadline_at"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.CustomID,
		arg.Delay,
		arg.Repeat,
		arg.Webhook,
		arg.DeadlineAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CustomID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Delay,
		&i.Repeat,
		&i.Webhook,
		&i.Status,
		&i.Executions,
		&i.DeadlineAt,
		&i.CompletedAt,
	)
	return i, err
}

const createJobLog = `-- name: CreateJobLog :one
INSERT INTO job_logs (
    job_id,
    started_at,
    completed_at,
    status_code,
    reason,
    payload,
    error,
    error_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, job_id, started_at, completed_at, status_code, reason, payload, error, error_type
`

type CreateJobLogParams struct {
	JobID       int64              `json:"job_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	StatusCode  pgtype.Int4        `json:"status_code"`
	Reason      pgtype.Text        `json:"reason"`
	Payload     pgtype.Text        `json:"payload"`
	Error       pgtype.Text        `json:"error"`
	ErrorType   pgtype.Text        `json:"error_type"`
}

func (q *Queries) CreateJobLog(ctx context.Context, arg CreateJobLogParams) (JobLog, error) {
	row := q.db.QueryRow(ctx, createJobLog,
		arg.JobID,
		arg.StartedAt,
		arg.CompletedAt,
		arg.StatusCode,
		arg.Reason,
		arg.Payload,
		arg.Error,
		arg.ErrorType,
	)
	var i JobLog
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.StatusCode,
		&i.Reason,
		&i.Payload,
		&i.Error,
		&i.ErrorType,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const getActiveJobs = `-- name: GetActiveJobs :many
SELECT id, custom_id, created_at, updated_at, delay, repeat, webhook, status, executions, deadline_at, completed_at FROM jobs
WHERE status = 'ACTIVE'
`

func (q *Queries) GetActiveJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, getActiveJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CustomID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Delay,
			&i.Repeat,
			&i.Webhook,
			&i.Status,
			&i.Executions,
			&i.DeadlineAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJob = `-- name: GetJob :one
SELECT id, custom_id, created_at, updated_at, delay, repeat, webhook, status, executions, deadline_at, completed_at FROM jobs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CustomID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Delay,
		&i.Repeat,
		&i.Webhook,
		&i.Status,
		&i.Executions,
		&i.DeadlineAt,
		&i.CompletedAt,
	)
	return i, err
}

const getJobByCustomID = `-- name: GetJobByCustomID :one
SELECT id, custom_id, created_at, updated_at, delay, repeat, webhook, status, executions, deadline_at, completed_at FROM jobs
WHERE custom_id = $1 LIMIT 1
`

func (q *Queries) GetJobByCustomID(ctx context.Context, customID pgtype.Text) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByCustomID, customID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CustomID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Delay,
		&i.Repeat,
		&i.Webhook,
		&i.Status,
		&i.Executions,
		&i.DeadlineAt,
		&i.CompletedAt,
	)
	return i, err
}

const getJobLogs = `-- name: GetJobLogs :many
SELECT id, job_id, started_at, completed_at, status_code, reason, payload, error, error_type FROM job_logs
WHERE job_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type GetJobLogsParams struct {
	JobID  int64 `json:"job_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetJobLogs(ctx context.Context, arg GetJobLogsParams) ([]JobLog, error) {
	rows, err := q.db.Query(ctx, getJobLogs, arg.JobID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobLog
	for rows.Next() {
		var i JobLog
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.StatusCode,
			&i.Reason,
			&i.Payload,
			&i.Error,
			&i.ErrorType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const processJob = `-- name: ProcessJob :one
UPDATE jobs
SET
    status = 'PROCESSING',
    updated_at = NOW()
WHERE
    id = $1 AND status = 'ACTIVE'
RETURNING id, custom_id, created_at, updated_at, delay, repeat, webhook, status, executions, deadline_at, completed_at
`

func (q *Queries) ProcessJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRow(ctx, processJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CustomID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Delay,
		&i.Repeat,
		&i.Webhook,
		&i.Status,
		&i.Executions,
		&i.DeadlineAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateJobAfterExecution = `-- name: UpdateJobAfterExecution :one
UPDATE jobs
SET
    status = $2,
    updated_at = $3,
    deadline_at = $4,
    executions = executions + 1
WHERE id = $1
RETURNING id, custom_id, created_at, updated_at, delay, repeat, webhook, status, executions, deadline_at, completed_at
`

type UpdateJobAfterExecutionParams struct {
	ID         int64              `json:"id"`
	Status     JobStatus          `json:"status"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeadlineAt pgtype.Timestamptz `json:"deadline_at"`
}

func (q *Queries) UpdateJobAfterExecution(ctx context.Context, arg UpdateJobAfterExecutionParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobAfterExecution,
		arg.ID,
		arg.Status,
		arg.UpdatedAt,
		arg.DeadlineAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CustomID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Delay,
		&i.Repeat,
		&i.Webhook,
		&i.Status,
		&i.Executions,
		&i.DeadlineAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET
    status = $2,
    updated_at = NOW(),
    completed_at = $3
WHERE id = $1
RETURNING id, custom_id, created_at, updated_at, delay, repeat, webhook, status, executions, deadline_at, completed_at
`

type UpdateJobStatusParams struct {
	ID          int64              `json:"id"`
	Status      JobStatus          `json:"status"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.ID, arg.Status, arg.CompletedAt)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CustomID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Delay,
		&i.Repeat,
		&i.Webhook,
		&i.Status,
		&i.Executions,
		&i.DeadlineAt,
		&i.CompletedAt,
	)
	return i, err
}
